name: Stable Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.DODA_APP_ID }}
          private-key: ${{ secrets.DODA_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # assume the just now pushed tag always points to latest commit on main
          fetch-depth: 0 # fetch full history so that `git branch --show-current` works
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Publish stable version
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute next version
        id: bump
        run: |
          TAG="${GITHUB_REF_NAME}"         # e.g., v1.2.3
          VERSION="${TAG#v}"               # 1.2.3
          IFS='.' read -ra parts <<< "$VERSION"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          next_patch=$((patch + 1))
          echo "next=${major}.${minor}.${next_patch}" >> $GITHUB_OUTPUT

      - name: Update gradle.properties to next SNAPSHOT
        run: |
          sed -i "s/^baseVersion=.*/baseVersion=${{ steps.bump.outputs.next }}-SNAPSHOT/" gradle.properties

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump to ${{ steps.bump.outputs.next }}-SNAPSHOT"
          file_pattern: gradle.properties
